# store zsh configuration in ~/.zsh
export ZDOTDIR=$HOME/.zsh

# source local binaries
export PATH="$HOME/.local/bin:$PATH"

# editors
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# less options
export LESS='-g -i -M -R -S -w -z-4'
