# store zsh configuration in ~/.zsh
export ZDOTDIR=$HOME/.zsh

# source local binaries
export PATH="$HOME/.local/bin:$PATH"

# force vim to use XDG path for vimrc
export VIMINIT='let $MYVIMRC="~/.config/nvim/init.vim" | source $MYVIMRC'

# editors
if (( $+commands[nvim] )); then
    export EDITOR='nvim'
    export VISUAL='nvim'
else
    export EDITOR='vim'
    export VISUAL='vim'
fi
export PAGER='less'

# less options
export LESS='-g -i -M -R -S -w -z-4'
