# use XDG paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# store zsh configuration in ~/.config/zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# source local binaries
export PATH="$HOME/.local/bin:$PATH"

# force vim to use XDG path for vimrc
export VIMINIT='let $MYVIMRC="~/.config/nvim/init.vim" | source $MYVIMRC'

# editors
if (( $+commands[nvim] )); then
    export EDITOR='nvim'
    export VISUAL='nvim'
else
    export EDITOR='vim'
    export VISUAL='vim'
fi
export PAGER='less'

# less options
export LESS='-g -i -M -R -S -w -z-4'
