# use XDG paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# store zsh configuration in ~/.config/zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# editors
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# less options
export LESS='-g -i -M -R -S -w -z-4'

# force timezone to PST
export TZ='America/Los_Angeles'
